version: "3.2"
services:
  frontend:
    image: ubulog/web-frontend
    deploy:
      labels:
        - traefik.port=80
        - traefik.ubulog.frontend.rule=Host:ubulog.com
    networks:
      - functions

networks:
  functions:
    external:
      name: func_functions